//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dota2chathub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string userid { get; set; }
        public string username { get; set; }
        public string language { get; set; }
        public string location { get; set; }
        public string steamid { get; set; }
        public string linkavatar { get; set; }
        public string displayname { get; set; }
        public Nullable<int> Totalscore { get; set; }
        public Nullable<System.DateTime> birthgday { get; set; }
        public Nullable<int> dotarank { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
